"""create skills tables

Revision ID: 5bcc1f10875a
Revises: fea7959113a4
Create Date: 2026-08-20 15:09:42.665755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5bcc1f10875a'
down_revision: Union[str, Sequence[str], None] = 'fea7959113a4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('normalized_name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_skills_normalized_name'), 'skills', ['normalized_name'], unique=True)
    op.create_table('freelancer_skills',
    sa.Column('freelancer_id', sa.UUID(), nullable=False),
    sa.Column('skill_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=50), nullable=False),
    sa.Column('years_experience', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['freelancer_id'], ['freelancer_profiles.user_id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['skill_id'], ['skills.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('freelancer_id', 'skill_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('freelancer_skills')
    op.drop_index(op.f('ix_skills_normalized_name'), table_name='skills')
    op.drop_table('skills')
    # ### end Alembic commands ###
